// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!jQVQPOOOOQO'#C_'#C_OOQO'#Ca'#CaOOQO'#Cc'#CcOOQO'#Ce'#CeOOQO'#Cg'#CgOOQO'#Ci'#CiOOQO'#Ck'#CkOOQO'#C^'#C^OOQO'#Cm'#CmQVQPOOOOQO-E6k-E6k",
  stateData: "n~OdOS~OSPOUQOWROYSO[TO^UO`VO~O",
  goto: "qbPPcgPgPgPgPgPgPgPkTXOYTWOYQYORZY",
  nodeNames: "⚠ Program Statement KeywordStmt Keyword NewOneStmt1 NewOne1 NewOneStmt2 NewOne2 NumberStmt Number OperatorStmt Operator IdentifierStmt Identifier ParensStmt Parens",
  maxTerm: 20,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "9p~Rjqr!sst!xxy!}yz!}z{!s{|!s}!O#S!P!Q!s![!]#[!^!_!s!_!`!s!`!a!s!f!g#b!}#O'c#T#U+h#V#W,i#W#X/Y#X#Y2R#Y#Z2q#Z#[3p#^#_,Q#`#a5z#a#b6m#d#e7V#f#g8X#g#h8q~!xO[~~!}OU~~#SO`~~#XP[~!`!a!s~#_P![!]!s~#eP#i#j#h~#kP#V#W#n~#qP#_#`#t~#wP!f!g#z~#}P#i#j$Q~$TP#V#W$W~$ZP#_#`$^~$aR!e!f$j!f!g%w!t!u&s~$mP#c#d$p~$sP#b#c$v~$yP#b#c$|~%PP#X#Y%S~%VP#V#W%Y~%]P#h#i%`~%cP#]#^%f~%iP#c#d%l~%oP#b#c%r~%wOW~~%zP#T#U%}~&QP#h#i&T~&WP#T#U&Z~&^P#U#V&a~&dP#T#U&g~&jP#g#h&m~&pP#X#Y%r~&vP#i#j&y~&|P#b#c'P~'SP#h#i'V~'YP#]#^']~'`P#a#b&m~'fRpq'o!Q!R(d#T#U)R~'rPXY'u~'xP]^'{~(OPYZ(R~(UP#P#Q(X~([P{|(_~(dOd~~(gP}!O(j~(mP!Z![(p~(sP#P#Q(v~(yP{|(|~)ROY~~)UP}!O)X~)[P#n#o)_~)bP!c!d)e~)hP}!O)k~)nP!|!})q~)tP#P#Q)w~)zP!}#O)}~*QP#T#U*T~*WP}!O*Z~*^P#n#o*a~*dP!c!d*g~*jP}!O*m~*pP!|!}*s~*vP!Q!R*y~*|P}!O+P~+SP!Z![+V~+YP#P#Q+]~+`Pz{+c~+hO^~~+kP#g#h+n~+qP#c#d+t~+wP#Y#Z+z~+}P#^#_,Q~,TP#c#d,W~,ZP#]#^,^~,aP#b#c,d~,iOS~~,lQ#`#a,r#c#d.Q~,uP#X#Y,x~,{P#T#U-O~-RP#f#g-U~-XP#R#S-[~-_P#a#b-b~-eP#T#U-h~-kP#V#W-n~-qP#f#g-t~-wP#c#d-z~-}P#g#h!x~.TP#b#c.W~.ZP#V#W.^~.aP#T#U.d~.gP#h#i.j~.mP#X#Y.p~.sP#b#c.v~.yP#T#U.|~/PP#h#i/S~/VP#X#Y,d~/]S#U#V!x#X#Y/i#]#^/o#f#g0e~/lP#Y#Z,d~/rP#g#h/u~/xP#h#i/{~0OP#]#^0R~0UP#b#c0X~0[P#V#W0_~0bP#h#i,d~0hP#c#d0k~0nP#d#e0q~0vPS~#R#S0y~0|P#T#U1P~1SP#`#a1V~1YP#`#a1]~1`P#R#S1c~1fP#h#i1i~1lP#T#U1o~1rP#U#V1u~1xP#`#a1{~2OP#X#Y-z~2UP#l#m2X~2[P#h#i2_~2bP#X#Y2e~2hP#b#c2k~2nP#W#X,d~2tQ#]#^2z#f#g3d~2}P#`#a3Q~3TP#h#i3W~3ZP#X#Y3^~3aP#f#g,d~3gP#c#d3j~3mP#a#b,d~3sQ#X#Y3y#f#g5[~3|P#h#i4P~4SP#R#S4V~4YQ#T#U4`#h#i1i~4cP#h#i4f~4iP#h#i4l~4oP#f#g4r~4uP#]#^4x~4{P#U#V5O~5RP#i#j5U~5XP#h#i1{~5_P#c#d5b~5eP#i#j5h~5kP#d#e5n~5qP!d!e5t~5wP#m#n,d~5}P#c#d6Q~6TQ#T#U6Z#V#W6a~6^P#W#X!x~6dP#T#U6g~6jP#`#a%r~6pP#T#U6s~6vP#V#W6y~6|P#f#g7P~7SP#c#d!x~7YQ#]#^7`#f#g7l~7cP#j#k7f~7iP#c#d0_~7oQ#]#^7u#c#d7{~7xP#b#c0_~8OP#^#_8R~8UP#X#Y0X~8[P#X#Y8_~8bP#b#c8e~8hP#T#U8k~8nP#a#b/S~8tS#X#Y9Q#[#]9W#]#^9d#c#d9j~9TP#`#a8R~9ZP#c#d9^~9aP#k#l-U~9gP#n#o/S~9mP#f#g0_",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
