// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Statement = 2,
  KeywordStmt = 3,
  Keyword = 4,
  NewOneStmt1 = 5,
  NewOne1 = 6,
  NewOneStmt2 = 7,
  NewOne2 = 8,
  NumberStmt = 9,
  Number = 10,
  OperatorStmt = 11,
  Operator = 12,
  IdentifierStmt = 13,
  Identifier = 14,
  ParensStmt = 15,
  Parens = 16
